# Generated by Django 3.1.3 on 2020-12-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('emp_username', models.CharField(max_length=20, unique=True)),
                ('emp_password', models.CharField(max_length=20)),
                ('emp_prefix', models.CharField(max_length=10)),
                ('emp_fname', models.CharField(max_length=20)),
                ('emp_lname', models.CharField(max_length=20)),
                ('emp_identification_code', models.CharField(max_length=13, unique=True)),
                ('emp_bdate', models.DateTimeField()),
                ('emp_image', models.ImageField(default='', upload_to='employee_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
