# Generated by Django 3.1.3 on 2020-12-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_userid', models.CharField(max_length=20)),
                ('rev_roomid', models.CharField(max_length=20)),
                ('rev_date', models.DateTimeField()),
                ('rev_timestart', models.TimeField()),
                ('rev_timestop', models.TimeField()),
            ],
        ),
    ]
