# Generated by Django 3.1.3 on 2020-12-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201228_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rev_finger1',
            field=models.CharField(default='', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='rev_finger2',
            field=models.CharField(default='', max_length=10000, null=True),
        ),
    ]
