# Generated by Django 3.1.3 on 2020-12-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201211_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(blank=True, default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
