# Generated by Django 3.1.3 on 2020-12-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201211_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.CharField(blank=True, default='', max_length=20, primary_key=True, serialize=False)),
                ('user_username', models.CharField(max_length=20, unique=True)),
                ('user_password', models.CharField(max_length=20)),
                ('user_prefix', models.CharField(max_length=10)),
                ('user_fname', models.CharField(max_length=20)),
                ('user_lname', models.CharField(max_length=20)),
                ('user_identification_code', models.CharField(max_length=13, unique=True)),
                ('user_bdate', models.DateTimeField()),
                ('user_image', models.ImageField(default='', upload_to='user_image')),
            ],
        ),
    ]
