# Generated by Django 3.1.3 on 2020-12-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201215_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_username',
            field=models.CharField(error_messages={'unique_error_message': 'This username has already been registered.'}, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
