# Generated by Django 3.1.3 on 2020-12-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20201217_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_image',
            field=models.ImageField(default='', upload_to='employee_image'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_image',
            field=models.ImageField(default='', upload_to='user_image'),
        ),
    ]
